aliyun:
  oss:
    bucketName: xxxxxxxxx
    endpoint: xxxxxxxxx
    keyId: xxxxxxxxx
    keySecret: xxxxxxxxx
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
server:
  port: 8130
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
