aliyun:
  sms:
    appcode: 5fa90ee9b5314c6194d0290d054ed434
    host: https://gyytz.market.alicloudapi.com
    method: POST
    path: /sms/smsSend
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    templateId: 908e94ccf08b4476ba6c876d13f084ad
server:
  port: 8120
spring:
  application:
    name: service-sms
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 2310956312
    port: 6379
    timeout: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  rabbitmq:
    host: 192.168.74.128
    port: 5672
    virtual-host: /
    username: root
    password: 123456
# feign配置
feign:
  #开启Feign对Sentinel的支持
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置

logging:
  level:
    com.softeem.rzb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口